package com.bgls.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsoleAllPropertiesEquals(Console expected, Console actual) {
        assertConsoleAutoGeneratedPropertiesEquals(expected, actual);
        assertConsoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsoleAllUpdatablePropertiesEquals(Console expected, Console actual) {
        assertConsoleUpdatableFieldsEquals(expected, actual);
        assertConsoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsoleAutoGeneratedPropertiesEquals(Console expected, Console actual) {
        assertThat(expected)
            .as("Verify Console auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsoleUpdatableFieldsEquals(Console expected, Console actual) {
        assertThat(expected)
            .as("Verify Console relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()))
            .satisfies(e -> assertThat(e.getImageContentType()).as("check image contenty type").isEqualTo(actual.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsoleUpdatableRelationshipsEquals(Console expected, Console actual) {}
}
